services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    # Expose Ollama API outside the container stack
    ports:
      - 11434:11434
    # 關鍵設定：調高檔案開啟上限
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ## GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: ${OLLAMA_GPU_DRIVER-nvidia}
    #           count: ${OLLAMA_GPU_COUNT-1}
    #           capabilities:
    #             - gpu
    #extra_hosts:
    #  - host.docker.internal:host-gateway
    networks:
      - web-app-bridge

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - tika
    ports:
      - 3000:8080
    environment:
      #- OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_SECRET_KEY=
      #- TIKA_SERVER_URL=http://tika:9998
      - TIKA_SERVER_URL=${TIKA_SERVER_URL}
    # 關鍵設定：調高檔案開啟上限
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - web-app-bridge

  traefik:
    image: "traefik"
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web-app-bridge

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    labels:
      - traefik.enable=true
      #- traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      #- traefik.http.routers.n8n.rule=Host(`localhost`)
      - traefik.http.routers.n8n.rule=Host(`${N8N_DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      #- traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.SSLHost=${N8N_DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      #- N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      #- N8N_HOST=localhost
      - N8N_HOST=${N8N_DOMAIN_NAME}
      - N8N_PORT=5678
      #- N8N_PROTOCOL=https
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      #- WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      #- WEBHOOK_URL=http://localhost:5678/
      #- WEBHOOK_URL=https://shack-earflap-euphemism.ngrok-free.dev/
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    depends_on:
      - ollama
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web-app-bridge

  ## Apache Tika Server
  tika:
    image: apache/tika:latest-full
    container_name: apache-tika
    #command: -c /tika-config.json
    #restart: on-failure
    restart: unless-stopped
    ports:
      - "9998:9998"
    #volumes:
    #  - ./sample-configs/vision/vlm-openai.json:/tika-config.json
    #  # - ./sample-configs/vision/vlm-claude.json:/tika-config.json
    #  # - ./sample-configs/vision/vlm-gemini.json:/tika-config.json
    environment:
      # 可根據需求限制 Java 記憶體大小（避免大型 PDF 造成 OOM 記憶體溢出）
      - TIKA_CHILD_JVM_OPTS=-Xmx4g
    depends_on:
      - ollama
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web-app-bridge

volumes:
  ollama: {}
  open-webui: {}
  n8n_data: {}
  traefik_data: {}

networks:
  web-app-bridge:
    external: true