services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    # Expose Ollama API outside the container stack
    ports:
      - 11434:11434
    # 關鍵設定：調高檔案開啟上限
    #ulimits:
    #  nofile:
    #    soft: 65536
    #    hard: 65536
    ## GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: ${OLLAMA_GPU_DRIVER-nvidia}
    #           count: ${OLLAMA_GPU_COUNT-1}
    #           capabilities:
    #             - gpu
    #extra_hosts:
    #  - host.docker.internal:host-gateway
    networks:
      - web-app-bridge

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API & Dashboard
      - "6334:6334" # gRPC API
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_SERVICE_READ_ONLY_API_KEY=${QDRANT_SERVICE_READ_ONLY_API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always
    networks:
      - web-app-bridge

  open-webui:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      ollama:
        condition: service_started
      qdrant:
        condition: service_started
      tika:
        condition: service_started
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - TIKA_SERVER_URL=${TIKA_SERVER_URL}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - ENABLE_PERSISTENT_CONFIG=${ENABLE_PERSISTENT_CONFIG}
      - VECTOR_DB=${VECTOR_DB}
      - QDRANT_URI=${QDRANT_URI}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_SERVICE_READ_ONLY_API_KEY=${QDRANT_SERVICE_READ_ONLY_API_KEY}
    # 關鍵設定：調高檔案開啟上限
    #ulimits:
    #  nofile:
    #    soft: 65536
    #    hard: 65536
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - web-app-bridge

  postgres:
    image: postgres:16
    container_name: postgres-16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - web-app-bridge

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      #- N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_HOST=${N8N_DOMAIN_NAME}
      - N8N_PORT=5678
      #- N8N_PROTOCOL=https
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      #- WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./local-files:/files
    depends_on:
      ollama:
        condition: service_started
      postgres:
        condition: service_healthy
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web-app-bridge

  ## Apache Tika Server
  tika:
    image: apache/tika:latest-full
    container_name: apache-tika
    #command: -c /tika-config.json
    #restart: on-failure
    restart: unless-stopped
    ports:
      - "9998:9998"
    #volumes:
    #  - ./sample-configs/vision/vlm-openai.json:/tika-config.json
    #  # - ./sample-configs/vision/vlm-claude.json:/tika-config.json
    #  # - ./sample-configs/vision/vlm-gemini.json:/tika-config.json
    environment:
      # 可根據需求限制 Java 記憶體大小（避免大型 PDF 造成 OOM 記憶體溢出）
      - TIKA_CHILD_JVM_OPTS=-Xmx4g
      # 關鍵：告訴 Tika Server 啟動時讀取自訂的設定檔
      #- TIKA_CONFIG=/tika-config.xml
    #volumes:
    #  # 將主機上的設定檔掛載到容器的根目錄
    #  - ./tika-config.xml:/tika-config.xml
    depends_on:
      ollama:
        condition: service_started
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web-app-bridge

volumes:
  ollama:
    driver: local
  open-webui:
    driver: local
  n8n_storage:
    driver: local
  qdrant_data:
    driver: local
  db_storage:
    driver: local
  traefik_data:
    driver: local

networks:
  web-app-bridge:
    external: true